<!DOCTYPE html>
<html lang="reactjs">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?= $title ?></title>
    <link href="<?= $favIcon ?>" rel="shortcut icon" type="image/png">

</head>

<body>


    <!-- --- main carusal--- -->
    <?php include_once('src/components/preLoader.php') ?>
    <?php include_once('src/views/layouts/navbar.php') ?>

    <!-- -------page header------ -->
    <?php require_once('src/components/pageHeader.php'); ?>
    <!-- -------page header------ -->


    <!-- -------life-insurance service ------ -->
    <div class="container py-5">
      
        <h5 class="service-side-title mt-3">Looking Beyond Listed Markets</h5>
        <p class="text-desgin">While listed shares dominate the investment landscape, a lesser-known avenue offers
            unique opportunities for investors-Unlisted Shares. Unlisted shares are those of privately held companies
            that are not available on any stock exchange.</p>

        <h5 class="service-side-title mt-5">How are unlisted shares different from listed shares?</h5>
        <h6 class="service-side-title mt-2">Market Accessibility:</h6>
        <p class="text-desgin">Unlisted shares are not traded on stock exchanges, making them less accessible to
            investors. Often unlisted shares are owned by founders, employees, venture capitalists, or private equity
            investors.</p>


        <h6 class="service-side-title">Liquidity:</h6>
        <p class="text-desgin">Unlisted shares have lower liquidity compared to listed shares. The absence of an
            organised market for buying and selling unlisted shares can make it challenging to exit investments quickly.
        </p>
        <h5 class="service-side-title mt-5">How can investors buy unlisted companies?</h5>
        <p class="text-desgin">There are two common ways of investing in unlisted companies.</p>

        <h6 class="service-side-title">Private Placement:</h6>
        <p class="text-desgin">Companies may offer shares to private individuals or institutions through private
            placements. Investors can participate in these offerings based on eligibility criteria and investment terms
            set by the issuing company.</p>
        <h6 class="service-side-title">Secondary Market:</h6>
        <p class="text-desgin">Specialised platforms, brokers, and marketplaces facilitate buying and selling unlisted
            shares. These platforms connect buyers and sellers and provide a regulated framework for transactions.</p>


        <h5 class="service-side-title mt-5">How to get information on unlisted shares?</h5>
        <p class="text-desgin">Obtaining information on unlisted shares can be more challenging compared to listed
            shares. However, investors can explore the following sources:</p>


        <h6 class="service-side-title">Company Disclosures:</h6>
        <p class="text-desgin">Companies issuing unlisted shares may provide information through private placement
            documents, investor presentations, and annual reports, although these may not be as extensive or publicly
            available as those of listed companies.</p>

        <p class="text-desgin">The most reliable place to get the data on an unlisted company would be the Ministry of
            Corporate Affairs website, as all companies have to submit their annual report and financial statement. One
            can quickly go there and check the information.</p>
        <h6 class="service-side-title">Research Firms:</h6>
        <p class="text-desgin">Some research firms specialise in analysing and providing insights on unlisted companies.
            Their reports can offer valuable information and analysis to investors.</p>

        <h5 class="service-side-title mt-5">Valuing unlisted shares</h5>
        <p class="text-desgin">Valuing unlisted shares involves a combination of qualitative and quantitative factors.
            Some methods commonly used for valuation include:</p>


        <h6 class="service-side-title">Earnings Multiplier:</h6>
        <p class="text-desgin">Assessing the company's earnings potential and applying a suitable multiplier based on
            industry benchmarks or comparable listed companies.</p>
        <h6 class="service-side-title">Net Asset Value (NAV):</h6>
        <p class="text-desgin">Determining the net value of the company's assets after deducting liabilities.</p>
        <h6 class="service-side-title">Discounted Cash Flow (DCF):</h6>
        <p class="text-desgin">Estimating the future cash flows generated by the company and discounting them to present
            value.</p>
        <p class="text-desgin">Valuation differences between unlisted and listed shares can be substantial. Unlisted
            shares tend to trade at a discount to their listed counterparts due to limited liquidity, restricted access,
            and more significant risks associated with unlisted companies.</p>

        <h5 class="service-side-title mt-5">Investing in unlisted shares offers several benefits:</h5>
        <p class="text-desgin">Meanwhile, not everything is great, and there are also challenges associated with
            investing in unlisted shares, including:</p>
        <h6 class="service-side-title">Liquidity Risk :</h6>
        <p class="text-desgin">Unlisted shares can be illiquid, making it difficult to exit investments when desired.
        </p>


        <h6 class="service-side-title">Lack of Information:</h6>
        <p class="text-desgin">Unlike listed companies, information on unlisted companies may be limited, making
            thorough due diligence crucial and challenging.</p>

        <h5 class="service-side-title mt-5">Who should invest in unlisted shares?</h5>
        <p class="text-desgin">Investing in unlisted shares is suitable for specific types of investors, including:</p>

        <h6 class="service-side-title">High Net Worth Individuals:</h6>
        <p class="text-desgin">Individuals with substantial financial resources and a higher risk appetite may consider
            unlisted shares as part of their investment strategy.</p>

        <h6 class="service-side-title">Sophisticated Investors:</h6>
        <p class="text-desgin">Experienced investors who can conduct thorough research and due diligence can capitalise
            on opportunities in unlisted shares.</p>

        <h6 class="service-side-title">Venture Capital and Private Equity Funds:</h6>
        <p class="text-desgin">These funds specialise in investing in unlisted companies and are well-positioned to
            assess their growth potential and manage associated risks.</p>
        <!-- <h5 class="service-side-title mt-5">How much exposure to this fund?</h5>
        <p class="text-desgin">A rule of thumb would be if you can put aside money to invest and pass on the share
            certificates to your grandchildren, you can consider the unlisted shares for that amount.</p>
        <p class="text-desgin">Unlisted shares offer a distinct avenue for investors seeking opportunities beyond listed
            markets. While they differ from listed shares regarding market accessibility and liquidity, they provide the
            potential for higher returns and diversification. Investors can purchase unlisted shares through private
            placements or secondary markets, and information can be obtained through company disclosures and research
            firms. Valuing unlisted shares requires a combination of quantitative and qualitative factors, and they
            generally trade at a discount compared to listed shares. Investing in unlisted shares has challenges,
            including liquidity risk and limited information availability. However, for high-net-worth individuals,
            sophisticated investors, and specialised funds, unlisted shares can be an attractive addition to a
            well-diversified investment portfolio.</p>
        <p class="text-desgin">AIFs are for sophisticated investors, high-net-worth individuals, institutional
            investors, and qualified institutional buyers. SEBI sets eligibility criteria for investing in AIFs, which
            typically consider minimum net worth, financial expertise, and risk-taking ability. These criteria ensure
            that AIF investments are accessed by knowledgeable investors who can bear the associated risks.</p>

        <h6 class="service-side-title">The rule of thumb to consider for AIF investors are</h6>
        <p class="text-desgin">The minimum investment required in the AIF is Rs 1 crore for an investor.</p>

        <p class="text-desgin">Employees, Directors, and fund managers can make a minimum investment of Rs 25 lakh.</p>

        <p class="text-desgin">Expect a lock-in period of around 3 yrs. Some AIFs may not have a lock-in, and some may
            have a lock-in of up to 5 years.</p>




        <h6 class="service-side-title">Potential for Higher Returns: </h6>
        <p class="text-desgin">Unlisted shares can provide attractive returns, primarily if invested in promising
            startups or high-growth private companies.</p>
        <h6 class="service-side-title">Diversification:</h6>
        <p class="text-desgin">Investing in unlisted shares allows investors to diversify their portfolios beyond
            traditional listed stocks and access sectors or companies unavailable in the public markets.</p>
        <h6 class="service-side-title"></h6>
        <p class="text-desgin"></p>
        <h6 class="service-side-title"></h6>
        <p class="text-desgin"></p>
        <h6 class="service-side-title"></h6>
        <p class="text-desgin"></p>


        <h6 class="service-side-title">Systematic Withdrawal Plan</h6>
        <p class="text-desgin">Systematic Withdrawal Plan (SWP) is highly convenient mutual fund facility which allows
            you to draw a fixed amount from your mutual fund scheme at a specified frequency (monthly, quarterly, annual
            etc). SWP cash-flows are generated by redeeming a certain number of units of your mutual fund scheme based
            on prevailing NAVs. The SWP amount is credited to your savings bank account every month or at any other
            interval specified by you in your SWP mandate. You can continue your SWP for a long period of time if the
            average return of the scheme is higher than the SWP withdrawal rate.</p> -->

        
    </div>
    </div>



    <!-- -------life-insurance service ------ -->



    <?php require_once('src/views/layouts/callus.php'); ?>
    <?php include_once('src/views/layouts/footer.php') ?>

</body>



</html>